import Head from 'next/head'
import { Navbar } from '@/components/Navbar'
import { WeatherCard } from '@/components/WeatherCard'
import { ForecastCard } from '@/components/ForecastCard'
import { useState, useEffect } from 'react'
import { currentConditions } from '@/services/accuweather'


export default function Home() {
  const [selectedLocation, setSelectedLocation] = useState<string>('')
  const [currentData, setCurrentData] = useState<any>({})

  useEffect(() => {
    const data =async () => {
      const currentLocationData = await currentConditions(selectedLocation)
      setCurrentData(currentLocationData)
    }
    data()
  }, [selectedLocation])

  const handleLocationSelect = (citiKey:string) => {
    setSelectedLocation(citiKey)
  }
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar onLocationSelect={handleLocationSelect} />
      <main className='p-2'>
        <h1 className='text-red-600'>Weather Project with Next</h1>
      </main>
      <section className='flex flex-col gap-2 p-2'>
        <WeatherCard currentDataInfo={currentData} />
        <ForecastCard />
      </section>
    </>
  )
}
