import { Inter } from 'next/font/google'
import Head from 'next/head'
import { Navbar } from '@/components/Navbar'
import { WeatherCard } from '@/components/WeatherCard'
import { ForecastCard } from '@/components/ForecastCard'
import prueba from '@/services/accuweather'


prueba('azul')
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='p-2'>
        <h1 className='text-red-600'>Weather Project with Next</h1>
      </main>
      <section className='flex flex-col gap-2 p-2'>
        <WeatherCard />
        <ForecastCard />
      </section>
    </>
  )
}
